# Generated by Django 5.0.14 on 2026-08-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnexchangerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
