# Generated by Django 5.0.14 on 2026-08-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('READY_FOR_PICKUP', 'Ready For Pickup'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('COMPLETED', 'Completed'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=30),
        ),
    ]
